/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  // Escanea el HTML y los JS para incluir solo las clases realmente usadas.
  content: ['./index.html', './assets/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e2e1',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#1c1b1b',
        'on-surface-variant': '#c5c9ae',
        'tertiary-fixed': '#e5e2e1',
        'surface-variant': '#353534',
        'on-tertiary': '#313030',
        'background': '#0a0a0a',
        'on-secondary-fixed-variant': '#454745',
        'inverse-on-surface': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f1f',
        'surface-bright': '#3a3939',
        'primary-fixed-dim': '#add512',
        'surface': '#0a0a0a',
        'on-secondary-container': '#b8b9b5',
        'secondary-fixed-dim': '#c6c7c3',
        'primary-fixed': '#d4ff45',
        'tertiary-container': '#e5e2e1',
        'outline-variant': '#444934',
        'inverse-primary': '#516600',
        'on-secondary': '#2f312e',
        'on-tertiary-container': '#656464',
        'on-primary': '#293500',
        'secondary-container': '#484947',
        'surface-tint': '#d4ff45',
        'surface-container-highest': '#353534',
        'primary': '#f4f4f0',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#3c4d00',
        'on-tertiary-fixed-variant': '#474746',
        'on-primary-container': '#566c00',
        'surface-container-low': '#1c1b1b',
        'on-error': '#690005',
        'on-surface': '#f4f4f0',
        'surface-dim': '#0a0a0a',
        'surface-container-high': '#2a2a2a',
        'on-error-container': '#ffdad6',
        'tertiary': '#ffffff',
        'secondary': '#c6c7c3',
        'primary-container': '#d4ff45',
        'tertiary-fixed-dim': '#c8c6c5',
        'outline': '#8f937b',
        'secondary-fixed': '#e2e3df',
        'on-secondary-fixed': '#1a1c1a',
        'on-primary-fixed': '#000000',
        'inverse-surface': '#e5e2e1',
        'obsidian': '#0A0A0A',
        'neon-lime': '#D4FF45',
        'cream': '#F4F4F0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'container-max': '1440px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-md': ['Space Grotesk'],
        'headline-lg-mobile': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'label-caps': ['Space Grotesk'],
        'display-lg': ['Space Grotesk'],
        'body-md': ['Inter'],
        'stats-number': ['Space Grotesk'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'stats-number': ['24px', { lineHeight: '1.0', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
